### ISSUE TITLE
Error object is not what's expected

### ISSUE THREAD

**Issue by Tyguy7** [kasperisager/sails-generate-auth#106]
Passport.js has a user create method that looks something like this:

```javascript
User.create(user, function (err, user) {
          if (err) {
            if (err.code === 'E_VALIDATION') {
              if (err.invalidAttributes.email) {
                req.flash('error', 'Error.Passport.Email.Exists');
              }
              else {
                req.flash('error', 'Error.Passport.User.Exists');
              }
            }

            return next(err);
          }

          query.user = user.id;

          Passport.create(query, function (err, passport) {
            // If a passport wasn't created, bail out
            if (err) {
              return next(err);
            }

            next(err, user);
          });
    });
}
```

It's trying to access attributes like err.code and err.invalidAttributes, but the object that is being surfaced is a raw Mongo error like this: "Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: E11000 duplicate key error index: database.user.$email_1  dup key: { : "user@email.com" }".  It never surfaces the error to the front end because it never catches err.code, or anything else.

It seem like waterline isn't doing something it's supposed to.  Or that sails-generate-auth has some other requirements for error handling just above the database level.

Any help would be much appreciated.

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
