### ISSUE TITLE
req.logIn() not exposed.

### ISSUE THREAD

**Issue by timestep** [kasperisager/sails-generate-auth#11]
Upon hitting the '/auth/local/' with this socket post request: 

```
socket.post('/auth/local/',{
				identifier: username,
				password: password,
				provider: 'local'
			}, 
```

I come with this error:

The user is found successfully, and returned via the callback, but the req.login() is not exposed.
```
break in api/controllers/AuthController.js:129
 127         return res.json('No User',500)
 128       }
 129       if(user){
 130         req.login(user, function (err) {
 131           // If an error was thrown, redirect the user to the login which should
debug> c

< /Users/kevin/Documents/dayPack/api/controllers/AuthController.js:130
<         req.login(user, function (err) {
<
<        ^
< TypeError: Object #<Object> has no method 'login'
<     at /Users/kevin/Documents/dayPack/api/controllers/AuthController.js:130:13
<     at Strategy.module.exports.strategy.success (/Users/kevin/Documents/dayPack/node_modules/passport/lib/middleware/authenticate.js:194:18)
<     at verified (/Users/kevin/Documents/dayPack/node_modules/passport-local/lib/passport-local/strategy.js:83:10)
<     at exports.login (/Users/kevin/Documents/dayPack/api/services/protocols/local.js:150:20)
program terminated
``

**Comment by timestep** [comment]
Hey, I just found this again.

I was having the same issue again  and found out I opened this a year ago...

It's still not implemented in the original documentation or suggested anywhere to implement this.

Can this be added on the main policy? Thanks.

**Comment by cScarlson** [comment]
Having same issue. I'm calling `socket.post(...)` via Bower-installed **sails.io.js**. I was authenticating before via Views and Postman just fine -- now `req.logIn` is undefined.

Has this issue been resolved yet?

**Comment by glebcha** [comment]
Faced the same issue.

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
