### ISSUE TITLE
Add JWT support

### ISSUE THREAD

**Issue by guiltry** [kasperisager/sails-generate-auth#135]
Is there any plan for JWT support ?

Thanks.

**Comment by kasperisager** [comment]
JWT is indeed different from bearer tokens; my bad! I'd love to implement JWT though when I have some time available.

**Comment by RWOverdijk** [comment]
I'd love to help out on this one if you have some pointers. I was recently pointed to [this repository](https://github.com/ghaiklor/generator-sails-rest-api) which takes, what seems like a slightly different approach. @ghaiklor also told me that it's best to move the `passport.initialize()` out of the policy.

Let's make this happen. Any thoughts?

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
