### ISSUE TITLE
config/routes.json file does not exist, replaced with .js?

### ISSUE THREAD

**Issue by grepped** [kasperisager/sails-generate-auth#142]
There is no routes.json file in my latest install of sails, there is only a config/routes.js file. I'm assuming this is an update in a recent version. Could an example be provided in the readme showing how to configure routes inside this new file?

**Comment by kasperisager** [comment]
That was an unfortunate typo; `config/routes.js` is the correct file :+1:

**Comment by grepped** [comment]
Confirmed, the lines work in the config/routes.js file. Could this be updated to avoid confusion?

**Comment by kasperisager** [comment]
Already taken care of!
