### ISSUE TITLE
policy authentication appearently not working on sails v.0.10.0-rc11

### ISSUE THREAD

**Issue by rafaelri** [kasperisager/sails-generate-auth#143]
Hi all,

 I tried to follow the instruction provided on the page to deny access to controllers based on a policy but I were unable to make it work as shown on the page. After a slight modification on policies/passport.js it worked, I added a single line shown below just before the next() invocation:
req.session.authenticated = (typeof(req.user) !== "undefined");

As I have not that much experience on Sails.js I can't say for sure whether I had missed something on the docs for sails-generate-auth or if it something has indeed changed on sails.js.

best regards,
Rafael

**Comment by kasperisager** [comment]
It should work if you just chain policies after the `passport` policy. This was not the case?
