### ISSUE TITLE
Linking All Accounts Together

### ISSUE THREAD

**Issue by tommykennedy** [kasperisager/sails-generate-auth#144]
Hi,

I was wondering how to link all accounts together. I want to have an account that links Local, Twitter, Facebook, Google etc.....

Is it possible with this framework?

I saw this example but was wondering if they was something built in to this generator. 
https://scotch.io/tutorials/easy-node-authentication-linking-all-accounts-together

Tom

**Comment by tommykennedy** [comment]
I found how to link by using the code below. However there is an issue after i logout after logging in with local strategy and connecting a social media account.

When I try to login in with the social media account (Twitter) it hangs at the twitter redirect page.

Any help would be greatly appreciated.


https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/services/passport.js#L173-L177

**Comment by kasperisager** [comment]
This functionality is fully supported by the generated auth layer: https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/services/passport.js#L158-L171. If a user is logged in and calls one of the authentication endpoints, a new passport will be created and assigned to the user.

**Comment by tommykennedy** [comment]
This links the accounts but Im unable to login with the connected account after linking. 

1. Register Local Account
2. Login
3. Connect Twitter, Facebook, Google Etc...
4. Logout
5. Login with Twitter, Facebook, Google Etc...

It stalls at this point......

Great framework by the way.
