### ISSUE TITLE
facebook login: no username, but have displayName

### ISSUE THREAD

**Issue by limulidae** [kasperisager/sails-generate-auth#145]
When I use facebook login,
I noticed username is always undefined.

  // If the profile object contains a username, add it to the user.
  if (profile.hasOwnProperty('username')) {
    user.username = profile.username;
  }

But I found a displayName is available.
Shoud it change/add displayName?

**Comment by kasperisager** [comment]
Facebook's `displayName` is fundamentally different from usernames; what you should probably be doing is request the `email` scope when authenticating with Facebook.
