### ISSUE TITLE
Confused by using the term 'next' to denote callbacks.

### ISSUE THREAD

**Issue by aantipov** [kasperisager/sails-generate-auth#146]
Hi

In strategy's verify callbacks, that are located in `/services/protocols/` folder, there the term `next` is used to denote callbacks (custom or built-in).
```
exports.login = function (req, identifier, password, next) {
  var isEmail = validator.isEmail(identifier)
    , query   = {};

  if (isEmail) {
    query.email = identifier;
  }
  else {
    query.username = identifier;
  }
...
```
It may confuse some users, because term 'next' is widely used to denote next middleware, not callbacks.
I think it would be better to stick to using the term 'done' in these cases, as it is done in passport documentation http://passportjs.org/guide/configure/:
```
passport.use(new LocalStrategy(
  function(username, password, done) {
    User.findOne({ username: username }, function (err, user) {
      if (err) { return done(err); }
      if (!user) {
        return done(null, false, { message: 'Incorrect username.' });
      }
      if (!user.validPassword(password)) {
        return done(null, false, { message: 'Incorrect password.' });
      }
      return done(null, user);
    });
  }
));
```

**Comment by kasperisager** [comment]
I see your point, although I personally prefer consistent naming of callbacks. That's why I stuck with `next` throughout the project. If anything, they should all be replaced by promises :smile:
