### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by prisonier** [kasperisager/sails-generate-auth#147]
I'm not sure if ts is correct but : 

- malicious-userb register with local strategy with following credential : 

```javascript
{
   username : user-b
   email : userA@user.com
   password : $uperpa$$wordYouCantH4ck
}
```
He have plain access to the app since there is no email verification

Now user-a just discover you app and he is lazzy, so he want to use facebook auth.

But since his email adress is userA@user.com, he is screwed, he will never be able to connect to your app unless he create a new email adress and register in local strategy ..... but remember, he is lazzy.

You just lost a customer right ?

**Comment by kasperisager** [comment]
I totally agree! This is a very valid concern. PRs are welcome :+1:

**Comment by prisonier** [comment]
I have the nose in the passport service since this morning but i can't figure where to implement email verification. We should choose a dependence to send email verification.

**Comment by kasperisager** [comment]
This should hopefully do the trick: https://www.npmjs.com/package/passport-email-verification

**Comment by prisonier** [comment]
Sorry i absolutely do not understand how this is working.
