### ISSUE TITLE
Where to retrieve facebook profile information (fullname & picture URL)?

### ISSUE THREAD

**Issue by prisonier** [kasperisager/sails-generate-auth#148]
I can't find where i can access to profile information other than email when a user has logged in with facebook auth. I would like to display the full name of the user and his picture but i don't find it in req.user once user is logged in.

Thanks for help

EDIT : i've found the issue #145, but i didn't get how to find displayName

**Comment by kasperisager** [comment]
Extended profile information isn't stored anywhere. You can either customise the generated files to store all profile information or you can access the stored auth tokens (https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/models/Passport.js#L63) and ping the corresponding API after registration.

**Comment by tommykennedy** [comment]
Is it possible to query the API using Passport? If not are there any example you have seen using Sails?

**Comment by kasperisager** [comment]
No, Passport only handles authentication. For API access you will have to either construct the HTTP queries yourself or use a wrapper (in the case of Facebook something like https://www.npmjs.com/package/facebook-api).

**Comment by tommykennedy** [comment]
Very helpful thank you. Cleared up real confusion.
