### ISSUE TITLE
How to show username on any page in sails application?

### ISSUE THREAD

**Issue by bORm** [kasperisager/sails-generate-auth#149]
Subj

**Comment by kasperisager** [comment]
You can access `user.username` in all controller-backed views.

**Comment by bORm** [comment]
‌‌user
‌ReferenceError: user is not defined

i can use only 
req.session.passport.user 
after connect to db and get my username

**Comment by kasperisager** [comment]
The `user` variable is only available in __views__, not __controllers__. Use `req.user` in controllers instead.

**Comment by bORm** [comment]
please show application where you show username in  layout view
i not understand you

**Comment by kasperisager** [comment]
I don't have one handy. The point is that you can access the `user` object in your views (https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/policies/passport.js#L30) and `req.user` in your controllers.

**Comment by bORm** [comment]
Okey, i see req.user Object in controller
but 
<%= user.username %> in homepage.ejs 
i see in browser error
{
  "path": "Z:\\home\\sails.loc\\www\\work\\views\\homepage.ejs"
}

**Comment by kasperisager** [comment]
You have to make sure that your view is connected to a controller. Static views ignore policies.

**Comment by bORm** [comment]
And no way to get access to this variable in static controllers?

**Comment by bORm** [comment]
Oh, thanks
close

**Comment by kasperisager** [comment]
No problem! You don't get far in this world without patience :smile: Cheers, and thanks!
