### ISSUE TITLE
How i can append data from social network to local?

### ISSUE THREAD

**Issue by bORm** [kasperisager/sails-generate-auth#150]
Subj
If i logged in ( after registration )
As example 
passport-facebook

I understand that I must add new route and action in controller
and then what?

I read 
https://github.com/kasperisager/sails-generate-auth/issues/144

// Scenario: A user is currently logged in and trying to connect a new passport.
// Action:   Create and assign a new passport to the user.

How create this action?

**Comment by tommykennedy** [comment]
Create a model called Profile that links to user. In a controller create the link. Below needs work but it should give you a hint. 

    facebook: function (req, res, next) {

        Passport.findOne({
            provider: "facebook",
            user: req.user.id
        }, function (err, passport) {
            if (err) {
                return next(err);
            }

            Wreck.get('https://graph.facebook.com/me?access_token=' + passport.tokens.accessToken, function (err, response, payload) {
                if (err) {
                    console.log("In error wreck call")
                }

                data = JSON.parse(payload);

                console.log(JSON.stringify(data));

                Profile.create({
                    user: req.user.id,
                    firstName: data.first_name,
                    lastName: data.last_name,
                    gender: data.gender,
                    socialID: data.id,
                },function (err, profile) {
                    console.log('In create profile callback');

                });

            });


            next(null,null);

        });


        res.send("Facebook Profile");

    }

**Comment by bORm** [comment]
i noticed that social data added to 
"passport": []
where it associated with local user by key ```user``` = ```id```

how add custom key from socila to users array?

**Comment by tommykennedy** [comment]
Wreck is a node module. I use it to query the rest API. Add this to your project

sudo npm install wreck --save

The model for profile is here. It should link automatically. User is the key. 

module.exports = {
    tableName: 'Profile',
    attributes: {
        user: {
            model: "User",
            required: true
        },
        socialID: {
            type: 'string'
        },        
        gender: {
            type: 'string'
        },        
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        profilePic: {
            type: 'string'
        }
    }
};
