### ISSUE TITLE
How do I get token to make requests?

### ISSUE THREAD

**Issue by misterch0c** [kasperisager/sails-generate-auth#153]
I'm succesfully logged but now how do I get my tokens to make request to the twitter api?
In the callback function I can see the tokens with 
`console.log(req.sessionStore.sessions[req.session.id]);`
output:
{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{},"flash":{},"oauth:twitter":{"oauth_token
":"oG1OMeDMlb43bw9hBgsfsdf47RvbjKOuE","oauth_token_secret":"BvNYdf545GOn1exxQ4vI8RO7M5bBi0gna"}}

But the problem is that I can't fetch data after the session id. 
`req.sessionStore.sessions[req.session.id]["oauth:twitter"]`
This is 'undefined' as well as .cookie...

**Comment by kasperisager** [comment]
All tokens are stored in the Passport model: https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/models/Passport.js#L61-L67

**Comment by misterch0c** [comment]
I'm sorry I'm a bit new to sails but how would I acces it then?

**Comment by kasperisager** [comment]
If you're using blueprints you should be able to access passports associated with a user out of the box as associated models will be joined in.
