### ISSUE TITLE
TypeError on Passport.create()

### ISSUE THREAD

**Issue by paulxtiseo** [kasperisager/sails-generate-auth#155]
So, I believe I have properly implemented sails-generate-auth per instructions. I can get the register page, enter data, and when I begin processing, I hit an error in line 63 of `api/services/protocols/local.js` that says `TypeError: undefined is not a function`.

If I comment out the subsequent `user.destroy()`, I can see that I have generated a User record in my postgresql database.

I am unsure how to debug why the `Passport.create()` fails. Any suggestions?

**Comment by kasperisager** [comment]
You'd need to use something like node-inspector for stepping through the execution of the auth flow. `user` should definitely not be `undefined` if you're seeing a record in your database.

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
