### ISSUE TITLE
SoundCloud not working

### ISSUE THREAD

**Issue by Eiryyy** [kasperisager/sails-generate-auth#156]
I used [jaredhanson/passport-soundcloud](https://github.com/jaredhanson/passport-soundcloud) but returned `profile` object was as follows.
```
{
  provider: 'soundcloud',
  id: xxxxx,
  displayName: 'xxxxx',
  _raw: '{"id":xxxxx,"kind":"user","permalink":"xxxxx","username":"xxxxx" ... }',
  _json: {
    id: xxxxx,
    kind: 'user',
    permalink: 'xxxxx',
    username: 'xxxxx',
    ...
  }
}
```
This hasn't `username` or `email`. How should we handle service like this?

**Comment by kasperisager** [comment]
Seems like a bug in the `passport-soundcloud` library. The JSON response obviously contains the username which should be part of the normalised profile.

**Comment by Eiryyy** [comment]
I've sent a PR to `passport-soundcloud`. Thanks.
