### ISSUE TITLE
req.user is undefined

### ISSUE THREAD

**Issue by cenobitedk** [kasperisager/sails-generate-auth#158]
Hello. I've set up Twitter, Github, Facebook and Google authentication.
So far I get a nice `user` in `req` with Twitter and Github, but when logging in with Facebook and Google I get `req.user undefined`.

I've added client id and secret for all passports and scope for Google. I see `redirect_uri` is set, but still with Facebook and Google I'm redirected back to the login page. Is there something I'm missing?

My app: https://github.com/cenobitedk/lego-exchange/tree/dev-sails/app

**Comment by cenobitedk** [comment]
Maybe @kasperisager can help me?

**Comment by kdelmonte** [comment]
Have you tried req.session.req.user?

**Comment by cenobitedk** [comment]
@kdelmonte thanks, but `req.session`is undefined.

**Comment by adicirstei** [comment]
have you checked the passport policy is getting executed? for example, the route for homepage is bypassing all controller and hence the policies applied. Make sure the passport policy is being executed.

```js
  '/': {
    view: 'homepage'
  },
```

**Comment by myangga** [comment]
I think that's fairly normal because default route is not under any controller. Basically you just display HTML page. Put your default page under a controller and works like a charm.
