### ISSUE TITLE
Req.session.passport ?

### ISSUE THREAD

**Issue by Geocloud** [kasperisager/sails-generate-auth#161]
Hello,

I used your module but i have a question for the community. I used passport-local.
In sessionAuth:
if (req.session.authenticated) {
    return next();
}

After logging, i don't have an access to the controller:
'TestController': ['sessionAuth'],

In SessionAuth, i see the request.session return that:
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: { user: 1 },
  flash: {} }

Is it valid ??
if(req.session.passport){
    return next();
  }

Thank you

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
