### ISSUE TITLE
Don't allow crypto to generate tokens with some characters

### ISSUE THREAD

**Issue by luiselizondo** [kasperisager/sails-generate-auth#164]
I'm using bearer strategy and it was working, the token was generated and I used it to make API requests. I reseted the token and I started to notice some strange behaviour because all API requests were responding with a 401.

Doing some digging I found out that my token was being read as:

```
2mZE4c8zJ6aYBPO7hw7ojlYWC5zW4KOBmky P2w7ph2qDfTkf6bOEQyW6pt/oBrx
```

When in fact, the token is: 

```
2mZE4c8zJ6aYBPO7hw7ojlYWC5zW4KOBmky+P2w7ph2qDfTkf6bOEQyW6pt/oBrx
```

This is probably because I'm sending the token as a query string and not included in the headers. If you can't see the difference between both tokens, there's a plus sign that is interpreted as a space. If I change the token manually to replace the + for any other character, everything works.

Unfortunately, I don't think is possible with crypto to generate a random token and exclude characters.

**Comment by yedhukrishnan** [comment]
That's sad!  Is there any other way to generate token with alphabets and characters? We can use that.

**Comment by luiselizondo** [comment]
There are other ways to generate random tokens, but before making a patch, I'd like confirmation from the maintainer that this is in fact a bug.

**Comment by yedhukrishnan** [comment]
The pull request for API authentication was given by me. I didn't think of this scenario! :(

**Comment by luiselizondo** [comment]
This is actually a bug waiting to happen, I don't know about the probability of this happening, but even if it is low, it will happen from time to time. The plus sign is just one of the signs that needs to be removed, I can think of at least another two character that needs to be removed, "&" and "?" both commonly used on queries.

The way I see it there's two ways to solve this:

1. Use https://www.npmjs.com/package/rand-token which allows to limit the characters:

```
var randtoken = require('rand-token').generator({
  chars: 'a-z'
});
```

The disadvantage of this method is that another module is needed. The advantage is that the token generated will always have the same size.

2. Using string.replace() to escape any possible conflicting character. This wouldn't require another extra module to install, but a token with any of the escaped characters would be smaller, or we could use the same replacing character. I don't know if this is a big issue since the probability of a token that includes only "&", "?" and "+" is virtually inexistent.

**Comment by imprecation** [comment]
So I ran into this problem and what I did was:
In api/services/protocols/local.js around line 64 it should have
var token = crypto.randomBytes(48).toString('base64');

put this under it to replaces the slashes and plus signs
token = token.replace(/\//g,'_').replace(/\+/g,'-');
and it seems to work.

**Comment by imprecation** [comment]
also I noticed if you use the token in a query it messes up the bluprint routes.  I think it's trying to run an action.  I got around this by deleting the query string once it authenticates.

**Comment by yedhukrishnan** [comment]
I'll fix it and give a pull request soon. Thanks for the help :)

**Comment by jcaspian** [comment]
By the way I found a work around is to use 

        var token = crypto.randomBytes(48).toString('hex');

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
