### ISSUE TITLE
No redirect after register

### ISSUE THREAD

**Issue by Knovour** [kasperisager/sails-generate-auth#165]
When I post `/auth/local/register`, it save the user data successfully, but it didn't redirect to the page I want in `AuthController`

And no error message output.

```js
passport.callback(req, res, function (err, user, challenges, statuses) {
      if (err || !user) {
        return tryAgain(challenges);
      }

      req.login(user, function (err) {
        if (err) {
          return tryAgain(err);
        }

        // Mark the session as authenticated to work with default Sails sessionAuth.js policy
        req.session.authenticated = true

       console.log(user)  // It has user data, but no redirect

        // Upon successful login, send the user to the homepage were req.user
        // will be available.
        res.redirect('/workspace');   //  Nothing happen
      });
    });
```

But use Google OAuth is ok

**Comment by laurynas-karvelis** [comment]
Same here, such issue appears erroneously, actually it does eventually redirect but that seem to take roughly 30 secs to a minute for node.js to actually make it happen.

I really think there must be a race condition somewhere, maybe while requiring some odd dependencies.

**Comment by 3bola** [comment]
Does log in work? Could the issue be in session handling?

**Comment by laurynas-karvelis** [comment]
The login itself does work. More and more I'm thinking that session handling is guilty, but cannot catch on any proof on that.

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
