### ISSUE TITLE
Can not register 

### ISSUE THREAD

**Issue by OnlyRefat** [kasperisager/sails-generate-auth#167]
Here what i have done is:

// ProfileController:
		home: function (req, res) {
    Passport
      .findOne({ protocol: 'local', user: req.user.id })
      .exec(function(err, passport) {
        return res.json({
          todo: 'home() is not implemented yet! But you are logged in :)',
          token: passport.accessToken
        });
      });
  }

//config/policy.js

  // '*': true,
   '*': ['passport', 'sessionAuth'],

  'Profile': {
    'showAll': ['passport', 'bearerAuth','sessionAuth'],
  },
  
  'auth': {
    '*': ['passport']
  }

But i can not register. when i click http://localhost:1337/auth/register it says  redirects to http://localhost:1337/auth/local/register and says the page you are trying to reach does not exit. 

Have i missed something in any file of the code??

**Comment by yedhukrishnan** [comment]
Do you have your code hosted somewhere?

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
