### ISSUE TITLE
Should README have a link to node.bcrypt.js?

### ISSUE THREAD

**Issue by serjrd** [kasperisager/sails-generate-auth#171]
Perhaps, it's a good idea to provide an alternative link for the C-module implementation of [bcrypt](https://github.com/ncb000gt/node.bcrypt.js). It's supposed to be faster than the bcryptjs (for which there is a link in the README).

**Comment by kasperisager** [comment]
This has already been discussed numerous times and I've settled with bcryptjs after a lot of feedback :+1:
