### ISSUE TITLE
No longer works with mongo with local strategy

### ISSUE THREAD

**Issue by myangga** [kasperisager/sails-generate-auth#174]
Hi, using Sails v0.11 and Mongo 2.6.5 (all latest as of today) on my Mac 10.10, I have following issue:
I install new sails project from scratch with:
```
sails generate test
cd test
npm install sails-generate-auth passport passport-local bcryptjs validator sails-mongo --save
```
Then I follow exact same steps as defined inside README.md.
If I keep my model connection to "localDiskDb", all is working as expected (login + registration).
If I add mongo details inside config/connections.js:
```
someMongodbServer: {
    adapter: 'sails-mongo',
    host: '127.0.0.1',
    // port: 27017,
    database: 'db_test'
  },
```
And then modify config/models like:
```
connection: 'someMongodbServer',
```
When I lift, if i try to login even with wrong data and press login button: I get my browser "loading" then get browser error message (like timeout) - stuck on URL /auth/local, and nothing in sails console. If I try to register with proper info, i get redirected to registration page with no error.
For info, my models are created inside my mongo instance, but no data is recorded for passport stuff. If I also setup sessions to be processed via mongo, it works. But one thing I noticed is that inside my session, if I try to register many times, each registration data submitted is stored inside my session entry (incremental - can see all submissions in!) and all passwords in clear...

I will continue to investigate but help would be very appreciated.
Thanks ;-)

**Comment by robksawyer** [comment]
I'm having the same issue. Bleh.

**Comment by myangga** [comment]
This is identified bug. Solution is specific and described below. You need to modify your connection string inside your connection.js file in config folder as:

```
my_mongo_cnx: {
    adapter: 'sails-mongo',
    host: '127.0.0.1', // defaults to `localhost` if omitted
    port: 27017, // defaults to 27017 if omitted
    user: '', // or omit if not relevant
    password: '', // or omit if not relevant
    database: 'my_mongo_db', // or omit if not relevant
    // Fix issue: The issue with v0.10.7 and v0.11.0-1 has been traced to inappropriate connection configurations (PR #277)
    // Walk around below
    poolSize: 5,
    socketOptions: {
        noDelay: true,
        connectTimeoutMS: 0,
        socketTimeoutMS: 0
    }
  },
```

**Comment by robksawyer** [comment]
I'm having problems with PostgreSQL as well. Is this a global thing for all dbs?

**Comment by myangga** [comment]
Don't know, I only work with Mongo. Best guy to talk about is Mike McNiel
directly ;-)

Le samedi 27 juin 2015, Rob Sawyer <notifications@github.com> a écrit :

> I'm having problems with PostgreSQL as well. Is this a global thing for
> all dbs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kasperisager/sails-generate-auth/issues/174#issuecomment-115934450>
> .
>


-- 

--

*Mikael Grandsire*
Mobile +33.(0)6.37.77.08.29
Email mikael.grandsire@gmail.com
