### ISSUE TITLE
Updating password on local account

### ISSUE THREAD

**Issue by latitudehopper** [kasperisager/sails-generate-auth#175]
I might have got the logic wrong on this. If I update the user model with a new password then my presumption is that the beforeUpdate method would be called and the new submitted password would be encrypted and stored in the passport? It seems as if the user record is updated but the password is not.

Here is my user.update controller.
```javascript
update: function(req, res) {
        var values = req.allParams();
        User.update(req.id, values).exec(function(err, users) {
            if(err){
                return res.error('nope');
            }
            return res.ok('good');
        });
    }
```
What have I missed?

**Comment by kasperisager** [comment]
Passwords are handled by the `Passport` model and not the `User` model :+1:

**Comment by benedictchen** [comment]
Password reset should be implemented, right?

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
