### ISSUE TITLE
Waterline validation error when authenticating with second account with the same email address and original is logged out

### ISSUE THREAD

**Issue by nwwells** [kasperisager/sails-generate-auth#176]
I logged in and created a user with facebook oauth, then that session must have expired (server reboot?) and then attempted to authenticate with google oauth (v2). I keep getting a "This email already exists. So try logging in." 

I debugged the issue and found that in services/passport.js#connect (lines 107-177) doesn't handle the case that a user is not logged in, but a user exists that has the same email and passport with a different service.

I haven't put the time in to grok the code yet, really. When I fix the issue for myself, I'll submit a PR.

**Comment by kasperisager** [comment]
This is by design as discussed in #28.

**Comment by nwwells** [comment]
OK, so is the issue that the error message is not very helpful? I guess I could change the message to "Hey, looks like we already created an account for that email address using a different service. Try logging in with the correct service"

**Comment by kasperisager** [comment]
Aye, you can tweak the error message in the generated locale file: https://github.com/kasperisager/sails-generate-auth/blob/master/templates/config/locales/en.json#L9
