### ISSUE TITLE
When i must to reset token?

### ISSUE THREAD

**Issue by kulakowka** [kasperisager/sails-generate-auth#178]
Please help me to understand?

After a successful login, I memorize the `currentUser` and the `accessToken` in the browser local storage. Then, i make requests to sails api with http header `Authorizaton: Bearer ...` and it's works!

However, I can not understand when I have to refresh the token? or i can use it every time?

**Comment by tommykennedy** [comment]
You can use the token until you want to logout at which point you remove it from local storage. If the token doesn't exist then you should login to get the token again and set it in local storage.

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
