### ISSUE TITLE
bearer.js auth returns an array of users

### ISSUE THREAD

**Issue by luiselizondo** [kasperisager/sails-generate-auth#179]
I don't know if this is actually a bug, but is certainly annoying.

The file services/protocols/bearer.js finds a user using User.findById, but it will return an array, when there should be only one user. Is there any reason why finding a user by id must return an array instead of a single object? I can make a patch but I want feedback first.

**Comment by tjwebb** [comment]
From the README:
> OBS: This generator is not currently maintained. Check out https://github.com/tjwebb/sails-auth for an actively maintained project based on this generator.

Please note that Sails.js is no longer actively maintained, and therefore sails-auth is also no longer maintained either. See https://github.com/tjwebb/sails-auth/issues/118

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
