### ISSUE TITLE
Updadting documentation

### ISSUE THREAD

**Issue by StoloADiane** [kasperisager/sails-generate-auth#180]
The passport.org website has completly changed.
http://passportjs.org/docs
All the documentation and de references in the comment are 404 link, please upade :)

**Comment by tjwebb** [comment]
From the README:
> OBS: This generator is not currently maintained. Check out https://github.com/tjwebb/sails-auth for an actively maintained project based on this generator.

Please note that Sails.js is no longer actively maintained, and therefore sails-auth is also no longer maintained either. See https://github.com/tjwebb/sails-auth/issues/118

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
