### ISSUE TITLE
Add scope paramerter in passport config for google

### ISSUE THREAD

**Issue by boubou191911** [kasperisager/sails-generate-auth#182]
When using passport-google-oauth it is mandatory to specify the scope to authenticate on google.
In the template config\passport.js I think it should be valuable to add this parameter in the google config part with some default value.
Example:
```javascript
  google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
      clientID: 'your-client-id',
      clientSecret: 'your-client-secret'
    },
    scope : 'openid profile email'
  },

**Comment by boubou191911** [comment]
Small correction as passport needs the e-mail to go through...
```javascript
  google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
      clientID: 'your-client-id',
      clientSecret: 'your-client-secret'
    },
    scope : 'openid profile email'
  },

**Comment by ShadeLotus** [comment]
+1

Would look like:  
    google: {
      name: 'Google',
      protocol: 'oauth2',
      strategy: require('passport-google-oauth').OAuth2Strategy,
      options: {
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET
        scope: ['email'] /* email is necessary for login behavior */
      }
    }

or similar

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
