### ISSUE TITLE
Example needed using 1 login system

### ISSUE THREAD

**Issue by adaptivedev** [kasperisager/sails-generate-auth#184]
The documentation is too abstract for newbies (like me).

It can be a lot more clear if you offer specific example data in your step-by-step instructions that actually works (if user enters valid credentials), without ANY guesswork.

Just use specific example data, not only generalized steps.

Thanks!

**Comment by tjwebb** [comment]
From the README:
> OBS: This generator is not currently maintained. Check out https://github.com/tjwebb/sails-auth for an actively maintained project based on this generator.

Please note that Sails.js is no longer actively maintained, and therefore sails-auth is also no longer maintained either. See https://github.com/tjwebb/sails-auth/issues/118

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
