### ISSUE TITLE
TypeError: HTTPBearerStrategy requires a verify callback.

### ISSUE THREAD

**Issue by stewhouston** [kasperisager/sails-generate-auth#185]
Passport/marlin bootstrap fails on 'sails lift' after following installation instructions provided in the README.

Receiving ```TypeError: HTTPBearerStrategy requires a verify callback```

If I comment out the bearer strategy in config/passport.js, I then get ```ERROR Error: HTTP Basic authentication strategy requires a verify function```

I am relatively new to Passport, so pardon me if I've overlooked something novice.

**Comment by kerihenare** [comment]
There's an issue with the documentation. It's options, then callback in the constructor.
Should be `passport.use(new BearerStrategy({ /* options */ }, function(token, done) {`

**Comment by yadavji83** [comment]
stuck at the same error. did you find any solution?

**Comment by stewhouston** [comment]
@yadavji83 - Apparently someone sent me a private message of some sort a few weeks back and I didn't see:

> There's an issue with the documentation. It's options, then callback in the constructor.
Should be passport.use(new BearerStrategy({ /* options */ }, function(token, done) {
https://guides.github.com/features/mastering-markdown/
