### ISSUE TITLE
Implement password reset on local strategy

### ISSUE THREAD

**Issue by benedictchen** [kasperisager/sails-generate-auth#187]
There is no way to reset a password if a user has lost their password.  Need a way to update the password.

**Comment by tjwebb** [comment]
From the README:
> OBS: This generator is not currently maintained. Check out https://github.com/tjwebb/sails-auth for an actively maintained project based on this generator.

Please note that Sails.js is no longer actively maintained, and therefore sails-auth is also no longer maintained. See https://github.com/tjwebb/sails-auth/issues/118

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
