### ISSUE TITLE
How to use one user with multiple authentication methods?

### ISSUE THREAD

**Issue by innobilehu** [kasperisager/sails-generate-auth#188]
Is it possible to use one user account with multiple authentication methods?
By me if a user was created by passport-google-oauth, if I try to log in with the facebook module (the user has the same e-mail address registered) I get only an error message (Error.Passport.Email.Exists)

**Comment by tjwebb** [comment]
From the README:
> OBS: This generator is not currently maintained. Check out https://github.com/tjwebb/sails-auth for an actively maintained project based on this generator.

Please note that Sails.js is no longer actively maintained, and therefore sails-auth is also no longer maintained. See https://github.com/tjwebb/sails-auth/issues/118

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
