### ISSUE TITLE
Override scope by user

### ISSUE THREAD

**Issue by Biromain** [kasperisager/sails-generate-auth#41]
Hi, i have a question.
I search a way to override scope value when a user login.

For example : 
I have a property in Passport model store extra scopes needed seem like (because user need more fonctionnalities) : 
```js
scopes: { type: 'array' }
```
I want to add extra scopes on scope defined in hard in `config/passport.js`.

After read the doc, we can define scope by second parameter on [authenticate](https://github.com/kasperisager/sails-generate-auth/blob/master/templates/api/services/passport.js#L185) but how can have acces to user info who try to login if already have user account ?
When code work, i can PR.

Thx in advance

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
